Models/AthleteModel.cs
using Olympics.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace _08_05_Olympics.Models
{
    public class AthleteModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public int Country_id { get; set; }
        public CountryModel Country { get; set; }
        public Dictionary<int, bool> Sports { get; set; } = new();
    }
}

Models/CountryModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace _08_05_Olympics.Models
{
    public class CountryModel
    {
        public int Id { get; set; }
        public string CountryName { get; set; }
        public string UNDP { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace _08_05_Olympics.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/SortFilterModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Olympics.Models
{
    public class SortFilterModel
    {
        public string Sort { get; set; }
        public List<string> SortSelection { get; set; } = new() { "Name", "Surname", "CountryName", "SportName" }; // name || surname || sport || country dropdown
        public string FilterCountry { get; set; } // 0 || lithuania || estija yra saliu dropdownas
        public string FilterSport { get; set; } // 0 || basketball || swimming yra sporto dropdownas
        public int FilterTeamActivity { get; set; } // -1 || 0 || 1 teamactivity dropdownas "pasirinkti actiitivy tipa"(-1), "not team"(0), "team" (1)
    }
}

Models/SportModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace _08_05_Olympics.Models
{
    public class SportModel
    {
        public int Id { get; set; }
        public string SportName { get; set; }
        public bool TeamActivity { get; set; }
    }
}

Models/ViewModels/IntegratedViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace _08_05_Olympics.Models.ViewModels
{
    public class IntegratedViewModel
    {
        public List<AthleteModel> Athletes { get; set; }
        public List<CountryModel> Countries { get; set; }
        public List<SportModel> Sports { get; set; }
    }
}

Models/ViewModels/JoinedViewModel.cs
using Olympics.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace _08_05_Olympics.Models.ViewModels
{
    public class JoinedViewModel
    {
        public List<AthleteModel> Athletes { get; set; }
        public List<CountryModel> Countries { get; set; }
        public List<SportModel> Sports { get; set; }
        public SortFilterModel SortFilter { get; set; }

    }
}

Controllers/AthletesController.cs
using _08_05_Olympics.Models;
using _08_05_Olympics.Models.ViewModels;
using _08_05_Olympics.Services;
using Microsoft.AspNetCore.Mvc;
using Olympics.Services;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;

namespace _08_05_Olympics.Controllers
{
    public class AthletesController : Controller
    {
        private readonly AthletesJoinedService _joinedService;
        private readonly AthletesDbService _athletesDbService;

        public AthletesController(AthletesJoinedService joinedService, AthletesDbService athletesDbService)
        {
            _joinedService = joinedService;
            _athletesDbService = athletesDbService;
        }

        public IActionResult Index()
        {
            JoinedViewModel model = _joinedService.GetModelForIndex();

            return View(model);
        }

        public IActionResult Create()
        {
            JoinedViewModel model = _joinedService.GetModelForCreate();

            return View(model);
        }

        [HttpPost]
        public IActionResult Create(List<AthleteModel> athletes)
        {
            _athletesDbService.AddAthlete(athletes[0]);

            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            JoinedViewModel model = _joinedService.GetModelForEdit(id);

            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(List<AthleteModel> athletes)
        {
            _athletesDbService.UpdateAthlete(athletes[0]);

            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            _athletesDbService.DeleteAthlete(id);
            return RedirectToAction("Index");
        }


        public IActionResult SortFilter(JoinedViewModel model)
        {
            JoinedViewModel sortmodel = _joinedService.GetModelForSortFilter(model.SortFilter);

            return View("Index", sortmodel);
        }
    }
}

Controllers/CountriesController.cs
using _08_05_Olympics.Models;
using _08_05_Olympics.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace _08_05_Olympics.Controllers
{
    public class CountriesController : Controller
    {
        private readonly CountriesDbService _dbService;

        public CountriesController(CountriesDbService dbService)
        {
            _dbService = dbService;
        }

        public IActionResult Index()
        {
            List<CountryModel> countries = _dbService.GetCountries();

            return View(countries);
        }

        public IActionResult Create()
        {
            CountryModel newCountry = new();

            return View(newCountry);
        }

        [HttpPost]
        public IActionResult Create(CountryModel country)
        {
            _dbService.AddCountry(country);

            return RedirectToAction("Index");
        }
    }
}

Controllers/HomeController.cs
using _08_05_Olympics.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace _08_05_Olympics.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/SportsController.cs
using _08_05_Olympics.Models;
using _08_05_Olympics.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace _08_05_Olympics.Controllers
{
    public class SportsController : Controller
    {
        private readonly SportsDbService _dbService;

        public SportsController(SportsDbService dbService)
        {
            _dbService = dbService;
        }

        public IActionResult Index()
        {
            List<SportModel> sports = _dbService.GetSports();

            return View(sports);
        }

        public IActionResult Create()
        {
            SportModel newSport = new();

            return View(newSport);
        }

        [HttpPost]
        public IActionResult Create(SportModel sport)
        {
            _dbService.AddSport(sport);

            return RedirectToAction("Index");
        }
    }
}

Views/Athletes/Create.cshtml
@model _08_05_Olympics.Models.ViewModels.IntegratedViewModel

<h2>Add an athlete</h2>

@using (Html.BeginForm("Create", "Athletes", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(m => m.Athletes[0].Name)
        @Html.TextBoxFor(m => m.Athletes[0].Name, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Athletes[0].Surname)
        @Html.TextBoxFor(m => m.Athletes[0].Surname, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Athletes[0].Country_id, "Select country")
        @Html.DropDownListFor(m => m.Athletes[0].Country_id, new SelectList(Model.Countries, "Id", "CountryName"), "", new { @class = "form-control" })
    </div>
    <div class="form-group">
        @for (var i = 0; i < Model.Sports.Count; i++)
        {
            var sport = Model.Sports[i];
            @Html.CheckBoxFor(m => m.Athletes[0].Sports[sport.Id])
            @Html.LabelFor(m => m.Athletes[0].Sports[sport.Id], sport.SportName)
        }
    </div>
    @Html.HiddenFor(m => m.Athletes[0].Id)
    <button type="submit" class="btn btn-primary">Add</button>
    @Html.ActionLink("Cancel", "Index", "Athletes", null, new { @class = "btn btn-secondary" })
} 

Views/Athletes/Edit.cshtml
@model _08_05_Olympics.Models.ViewModels.JoinedViewModel
@{
    ViewData["Title"] = "Edit Athlete Data";
}

<h2>Edit athlete data</h2>

@using (Html.BeginForm("Edit", "Athletes", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(m => m.Athletes[0].Name)
        @Html.TextBoxFor(m => m.Athletes[0].Name, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Athletes[0].Surname)
        @Html.TextBoxFor(m => m.Athletes[0].Surname, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Athletes[0].Country_id, "Select country")
        @Html.DropDownListFor(m => m.Athletes[0].Country_id, new SelectList(Model.Countries, "Id", "CountryName"), "", new { @class = "form-control" })
    </div>
    <div class="checkbox mb-3">
        @for (var i = 0; i < Model.Sports.Count; i++)
        {
            var sport = Model.Sports[i];
            <label class="mr-4">
                @Html.CheckBoxFor(m => m.Athletes[0].Sports[sport.Id])
                @sport.SportName
            </label>
        }
    </div>
    @Html.HiddenFor(m => m.Athletes[0].Id)
    <button type="submit" class="btn btn-primary">Save changes</button>
    @Html.ActionLink("Cancel", "Index", "Athletes", null, new { @class = "btn btn-secondary" })
}

Views/Athletes/Index.cshtml
@model _08_05_Olympics.Models.ViewModels.JoinedViewModel

<h2 class="d-inline-block mb-4">Athletes</h2>

@Html.ActionLink("Add an athlete", "Create", "Athletes", null, new { @class = "btn btn-primary float-right" })
<p></p>


@using (Html.BeginForm("SortFilter", "Athletes", FormMethod.Post))
{
    <div>
        @Html.LabelFor(m => m.Athletes[0].Country_id, "Select how to sort:")
        @Html.DropDownListFor(m => m.SortFilter.Sort, new SelectList(Model.SortFilter.SortSelection), "", new { @class = "form-control" })
        <div class="form-group">
            @Html.LabelFor(m => m.SortFilter.FilterSport, "Select what sport you want to filter by: ")
            @Html.DropDownListFor(m => m.SortFilter.FilterSport, new SelectList(Model.Sports.Select(s => s.SportName)), "", new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.SortFilter.FilterCountry, "Select what country you want to filter by: ")
            @Html.DropDownListFor(m => m.SortFilter.FilterCountry, new SelectList(Model.Countries.Select(s => s.CountryName)), "", new { @class = "form-control" })
        </div>
        <button type="submit" class="btn btn-primary">Sort</button>
    </div>

}

@if (Model.Athletes.Count == 0)
{
    <p>The Olympics games this ear are kinda slow..</p>
}
else
{
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th class="text-center">Name</th>
                <th class="text-center">Surname</th>
                <th class="text-center">Country</th>
                <th class="text-center">Sports</th>
                <th class="text-center">Action Buttons</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var athlete in Model.Athletes)
            {
            <tr>
                <td class="text-center">@athlete.Name</td>
                <td class="text-center">@athlete.Surname</td>
                <td class="text-center">@athlete.Country.CountryName</td>
                <td class="text-center">
                    <ul class="m-0">
                        @for (int i = 0; i < athlete.Sports.Count; i++)
                        {
                            int sportId = athlete.Sports.ElementAt(i).Key;
                            <li>@Model.Sports.Single(s => s.Id == sportId).SportName</li>
                        }
                    </ul>
                </td>
                <td class="btn-toolbar">
                    <button>@Html.ActionLink("Delete", "Delete", "Athletes", new { id = athlete.Id }, new { @class = "btn btn-danger", @style = "color:white" })</button>
                    <button>@Html.ActionLink("Edit", "Edit", "Athletes", new { id = athlete.Id }, new { @class = "btn btn-warning", @style = "color:white" })</button>
                    <ul></ul>
                </td>
            </tr>
            }
        </tbody>
    </table>
}

Views/Countries/Create.cshtml
@model CountryModel

<h2>Add a country</h2>

@using (Html.BeginForm("Create", "Countries", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(c => c.CountryName, "CountryName of country")
        @Html.TextBoxFor(c => c.CountryName, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(c => c.UNDP, "Country code (3 letters)")
        @Html.TextBoxFor(c => c.UNDP, new { @class = "form-control" })
    </div>
    @Html.HiddenFor(c => c.Id)
    <button type="submit" class="btn btn-primary">Add</button>
    @Html.ActionLink("Cancel", "Index", "Countries", null, new { @class = "btn btn-secondary" })
} 

Views/Countries/Index.cshtml
@model List<CountryModel>

<h2 class="d-inline-block mb-4">Countries</h2>

@Html.ActionLink("Add a country", "Create", "Countries", null, new { @class = "btn btn-primary float-right" })

@if (Model.Count == 0)
{
    <p>There are no countries.</p>
}
else
{
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th class="text-center">Id</th>
                <th class="text-center">CountryName</th>
                <th class="text-center">UNDP</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var country in Model)
            {
                <tr>
                    <td class="text-center">@country.Id</td>
                    <td class="text-center">@country.CountryName</td>
                    <td class="text-center">@country.UNDP</td>
                </tr>
            }
        </tbody>
    </table>
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Olympics</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Olympics</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Athletes" asp-action="Index">List of Athletes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sports" asp-action="Index">List of Sports</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Countries" asp-action="Index">List of Countries</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Olympics - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Sports/Create.cshtml
@model SportModel

<h2>Add a sport</h2>

@using (Html.BeginForm("Create", "Sports", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(s => s.SportName, "Name of sport")
        @Html.TextBoxFor(s => s.SportName, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(s => s.TeamActivity, "Team activity")
        @Html.CheckBoxFor(s => s.TeamActivity, new { @class = "form-control" })
    </div>
    @Html.HiddenFor(s => s.Id)
    <button type="submit" class="btn btn-primary">Add</button>
    @Html.ActionLink("Cancel", "Index", "Sports", null, new { @class = "btn btn-secondary" })
} 

Views/Sports/Index.cshtml
@model List<SportModel>

<h2 class="d-inline-block mb-4">List of Sports</h2>

@Html.ActionLink("Add a sport", "Create", "Sports", null, new { @class = "btn btn-primary float-right" })

@if (Model.Count == 0)
{
    <p>There are no sports.</p>
}
else
{
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th class="text-center">Id</th>
                <th class="text-center">SportList</th>
                <th class="text-center">Team Activity</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var sport in Model)
            {
                <tr>
                    <td class="text-center">@sport.Id</td>
                    <td class="text-center">@sport.SportName</td>
                    <td class="text-center">@{ var value = sport.TeamActivity ? "Yes" : "No"; }@value</td>
                </tr>
            }
        </tbody>
    </table>
}